CREATE SCHEMA IF NOT EXISTS deux;

CREATE TABLE IF NOT EXISTS deux.providers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    account_id VARCHAR NOT NULL,
    url VARCHAR NOT NULL
);